<template>
    <div class="MainBox">
        <div class="FormBox">
            <h1>Buat Event Baru</h1>
            <div class="FormContent">
                <h2>Informasi Penting</h2>
                <div class="row">
                    <div class="col">
                        <b-form-group label="Judul Event" label-for="event-title">
                        <b-form-input id="event-title" v-model="eventTitle" />
                        </b-form-group>
                    </div>
                    <div class="col-8">
                        <b-form-group label="Subjudul" label-for="event-subtitle">
                        <b-form-input id="event-subtitle" v-model="eventSubtitle" />
                        </b-form-group>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                    <b-form-group label="Waktu Mulai" label-for="event-date">
                        <b-form-input id="event-date" v-model="eventStartTime" type="datetime-local" />
                    </b-form-group>
                    </div>
                    <div class="col">
                    <b-form-group label="Waktu Selesai" label-for="event-end-date">
                        <b-form-input id="event-end-date" v-model="eventEndTime" type="datetime-local" />
                    </b-form-group>
                    </div>
                    <div class="col-8">
                    <b-form-group label="Lokasi" label-for="event-location">
                        <b-form-input id="event-location" v-model="eventLocation" />
                    </b-form-group>
                    </div>
                </div>
            </div>

            <div class="FormContent">
                <h2>Kategori dan Harga Tiket</h2>
                <div v-for="(ticketCategory, index) in ticketCategories" :key="index">
                    <b-form-group label="Nama Kategori Tiket">
                        <b-form-input v-model="ticketCategory.name" />
                    </b-form-group>
                    <b-form-group label="Jumlah Tiket">
                        <b-form-input v-model="ticketCategory.quantity" type="number" />
                    </b-form-group>
                    <b-form-group label="Harga per Tiket">
                        <b-form-input v-model="ticketCategory.price" type="number" />
                    </b-form-group>
                </div>
                <b-button >Tambah Kategori Tiket</b-button>
            </div>
            <div class="FormContent">
                <h2>Konten Promosional</h2>
                <div>
                    <label for="event-poster">Unggah Poster Event</label>
                    <div class="row">
                        <div class="col">
                            <div class="FileUpload">
                                <div
                                    class="UploadArea"
                                    @dragover.prevent
                                    @drop.prevent="handleDrop"
                                    @click="$refs.fileInput.click()"
                                >
                                    <b-icon-upload aria-setsize="lg"/>
                                    <p>Click or drag file to this area to upload</p>
                                    <p>Support for a single or bulk upload. Strictly prohibit from uploading NSFW images.</p>
                                </div>
                                <input
                                    ref="fileInput"
                                    type="file"
                                    accept=".png, .jpg, .jpeg, .gif"
                                    style="display: none"
                                    multiple
                                    @change="handleFileSelect"
                                />
                            </div>
                        </div>
                        <div class="col">
                            <b-form-group label="Tags" label-for="event-tag">
                                <b-form-input id="event-tag" v-model="eventTags" />
                            </b-form-group>
                        </div>
                    </div>
                </div>
                <b-form-group label="Deskripsi Event">
                    <div class="AutoGenerateContainer">
                        <div class="RemainingChances">
                            Sisa {{ remainingChances }} kesempatan
                        </div>
                        <b-button size="sm" class="GenerateButton" @click="autoGenerateDesc">Auto Generate</b-button>
                        
                    </div>
                    <wysiwyg v-model="eventDescription" />
                </b-form-group>
                <div>
                    <b-button>Lihat Preview</b-button>
                </div>
            </div>
        </div>
        <div class="BottomButtons">
            <b-button class="CancelButton">Cancel</b-button>
            <b-button>Simpan</b-button>
        </div>
    </div>
</template>

<script>
import Vue from 'vue';
import wysiwyg from "vue-wysiwyg"; 
import "vue-wysiwyg/dist/vueWysiwyg.css";

Vue.use(wysiwyg, {
    hideModules: { "hyperLink": true },
    forcePlainTextOnPaste: true,
    maxHeight: "30rem",
});
export default {
    name: 'EventCreateEvents',
    
    data() {
        return {
            eventTitle: '',
            eventSubtitle:'',
            eventStartTime: '',
            eventEndTime: '',
            eventLocation: '',
            ticketCategories: [],
            eventTags:'',
            eventDescription: null,
            eventPoster: null,
            chances:4,

        }
    },
    computed: {
      content() {
        return this.eventDescription;
      },
      remainingChances() {
        console.log("remaining", this.chances)
        return this.chances; // You can add formatting or logic here if needed
        
    }
    },
    watch: {
    eventStartTime(newValue, oldValue) {
        this.checkTimeValidity();
    },
    eventEndTime(newValue, oldValue) {
        this.checkTimeValidity();
    },
},
    methods:{
        checkTimeValidity() {
            if (new Date(this.eventStartTime) >= new Date(this.eventEndTime)) {
                alert("Waktu Mulai harus lebih awal dari Waktu Selesai.");
                this.eventStartTime = '';
                this.eventEndTime = '';
            }
        },
        autoGenerateDesc(){
            if(this.chances === 0){
                alert("Kesempatan habis")
            }
            else{
                this.chances--;
                console.log(this.chances)
            }
            
        },
        handleDrop(e) {
            this.handleFiles(e.dataTransfer.files);
        },
        handleFileSelect(e) {
            this.handleFiles(e.target.files);
        },
        handleFiles(files) {
            const allowedTypes = ['image/png', 'image/jpeg', 'image/gif'];
            const maxFileSize = 10 * 1024 * 1024; // 10 MB (adjust as needed)
            for (let i = 0; i < files.length; i++) {
                if (!allowedTypes.includes(files[i].type)) {
                    alert('File type not supported. Please upload PNG, JPEG, or GIF files only.');
                    return;
                }
                if (files[i].size > maxFileSize) {
                    alert('File size exceeds the limit. Please upload files up to 5 MB.');
                    return;
                }
            }
            console.log(files);
        },
    },

}
</script>
<style scoped>
.MainBox{
    display: flex;
    width: 100%;
    justify-content: center;
    align-content: center;
    flex-direction: column;
    margin-bottom: 1rem;
}
.FormBox{
    width: 85%;
    max-width: 62.5rem; 
    margin: 0 auto;
    overflow-y: auto;
    background-color: white;
    padding: 20px;
}
.FormContent{
    margin:0.125rem;
    padding:0.5rem;
    border:solid #f2f0e9 1px;
    border-radius: 0.25rem;
}
h1{
    font-size: 1.5rem;   
}
h2{
    font-size: 1.25rem;
}
.row {
    display: flex;
    flex-wrap: wrap;
    margin-bottom: 10px;
}
.col {
    flex: 1;
    margin-right: 10px;
}
.col-8 {
    flex: 2;
    margin-right: 10px;
}
.BottomButtons {
    display: flex;
    justify-content: flex-end; 
    margin-top: 0.5rem;
    width: 85%;
    max-width: 62.5rem; 
    margin: 0 auto;
    padding-right: 1.25rem;
    gap: 1rem;
}
.CancelButton{
    color: #035037;
    background-color: #f2f0e9;
    border-color: #035037;
}
.AutoGenerateContainer{
    display: flex;
    justify-content: flex-end;
    gap:1rem;
    margin:0.5rem;
    width: 100%;
    max-width: 62.5rem;
    padding-right: 0.5rem;
}
.GenerateButton {
    background-color: #035037;
}
.RemainingChances {
    display: flex;
    align-items: center; /* Vertically center the content */
}
.FileUpload {
  width: 100%;
  height: 200px;
  border: 2px dashed #ccc;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  cursor: pointer;
  background-color: #F1F1F5;
}

.UploadArea {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
}

.UploadArea img {
  width: 50px;
  height: 50px;
  margin-bottom: 10px;
}
</style>